// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tosrzomcfuscqpjzptvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvc3J6b21jZnVzY3FwanpwdHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODE3MzUsImV4cCI6MjA3MzY1NzczNX0.CLnMt0eXohJN4srlmy2C7D7Yqug4GAi3T2L2mDTPqkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});